# Generated by Django 3.0.3 on 2020-04-30 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200429_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('catalog.can_mark_returned', 'Can edit the book'),)},
        ),
    ]
